import { Injectable } from '@angular/core';
import { City } from '../models/city.model';
import { Attraction } from '../models/attraction.model';
import { TourismEvent } from '../models/event.model';

@Injectable({ providedIn: 'root' })
export class MockDataService {

  readonly cities: City[] = [
    {
      id: '1', nameAr: 'الرياض', nameEn: 'Riyadh',
      descriptionAr: 'عاصمة المملكة العربية السعودية ومركزها الاقتصادي والإداري، مدينة تجمع بين الأصالة والحداثة. تتميز بناطحات السحاب الشاهقة والمراكز التجارية الضخمة إلى جانب الأحياء التاريخية والتراثية العريقة.',
      descriptionEn: 'The capital and economic hub of Saudi Arabia, Riyadh is a city that blends tradition with modernity. Towering skyscrapers and massive commercial centers coexist alongside historic and heritage districts.',
      shortDescAr: 'عاصمة المملكة ومركزها الاقتصادي',
      shortDescEn: 'The Kingdom\'s capital and economic hub',
      image: 'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1586724237569-f3d0c1dee8c6?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1630501594958-b40d4f2adc95?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Riyadh Region', regionAr: 'منطقة الرياض',
      population: '7.6 مليون', area: '1,798 كم²',
      timezone: 'AST (UTC+3)', climate: 'Desert (Hot & Dry)', climateAr: 'صحراوي (حار وجاف)',
      rating: 4.7, reviewCount: 12400, featured: true,
      tags: ['capital', 'modern', 'shopping', 'heritage'],
      tagsAr: ['العاصمة', 'حديثة', 'تسوق', 'تراث'],
      coordinates: { lat: 24.7136, lng: 46.6753 },
      bestTimeToVisit: 'November - March', bestTimeToVisitAr: 'نوفمبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 45, hotelCount: 320, restaurantCount: 1200, eventCount: 28,
    },
    {
      id: '2', nameAr: 'جدة', nameEn: 'Jeddah',
      descriptionAr: 'بوابة الحرمين الشريفين وعروس البحر الأحمر، مدينة تمتزج فيها الثقافات وتلتقي فيها التجارات منذ قرون. تشتهر بكورنيشها الطويل وحيها التاريخي العريق.',
      descriptionEn: 'The gateway to the Two Holy Mosques and bride of the Red Sea, Jeddah is a city where cultures blend and trade has flourished for centuries. Famous for its long corniche and historic old district.',
      shortDescAr: 'عروس البحر الأحمر وبوابة الحرمين',
      shortDescEn: 'Bride of the Red Sea and gateway to the Holy Mosques',
      image: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Makkah Region', regionAr: 'منطقة مكة المكرمة',
      population: '4.7 مليون', area: '1,686 كم²',
      timezone: 'AST (UTC+3)', climate: 'Hot & Humid', climateAr: 'حار رطب',
      rating: 4.8, reviewCount: 18600, featured: true,
      tags: ['coastal', 'heritage', 'diving', 'culture'],
      tagsAr: ['ساحلية', 'تراث', 'غوص', 'ثقافة'],
      coordinates: { lat: 21.4858, lng: 39.1925 },
      bestTimeToVisit: 'October - April', bestTimeToVisitAr: 'أكتوبر - أبريل',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 38, hotelCount: 280, restaurantCount: 950, eventCount: 22,
    },
    {
      id: '3', nameAr: 'العُلا', nameEn: 'AlUla',
      descriptionAr: 'واحة التاريخ في قلب الجزيرة العربية، تحتضن حضارات آلاف السنين. موطن مدائن صالح، المدينة النبطية المحفورة في الصخر والمدرجة ضمن التراث العالمي لليونسكو.',
      descriptionEn: 'An oasis of history in the heart of Arabia, AlUla cradles civilizations thousands of years old. Home to Hegra (Madain Saleh), the Nabataean city carved in rock and a UNESCO World Heritage Site.',
      shortDescAr: 'واحة التاريخ وجوهرة التراث العالمي',
      shortDescEn: 'An oasis of history and a UNESCO gem',
      image: 'https://images.unsplash.com/photo-1590764508404-09c67fff4358?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1590764508404-09c67fff4358?auto=format&fit=crop&w=800&q=80',
        'https://images.unsplash.com/photo-1627384113716-e5e8a04c7f5b?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Al Madinah Region', regionAr: 'منطقة المدينة المنورة',
      population: '75,000', area: '22,561 كم²',
      timezone: 'AST (UTC+3)', climate: 'Desert', climateAr: 'صحراوي',
      rating: 4.9, reviewCount: 8200, featured: true,
      tags: ['heritage', 'UNESCO', 'desert', 'history'],
      tagsAr: ['تراث', 'يونسكو', 'صحراء', 'تاريخ'],
      coordinates: { lat: 26.6107, lng: 37.9199 },
      bestTimeToVisit: 'October - March', bestTimeToVisitAr: 'أكتوبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 22, hotelCount: 45, restaurantCount: 80, eventCount: 12,
    },
    {
      id: '4', nameAr: 'أبها', nameEn: 'Abha',
      descriptionAr: 'عاصمة منطقة عسير وجوهرة الجنوب، تتميز بطبيعتها الجبلية الخلابة وأجوائها المعتدلة على مدار السنة. تشتهر بضبابها الرومانسي وقراها التراثية الملونة.',
      descriptionEn: 'Capital of Asir region and the gem of the south, Abha is distinguished by its stunning mountain scenery and mild weather year-round. Famous for its romantic fog and colorful heritage villages.',
      shortDescAr: 'جوهرة الجنوب والعروس الجبلية',
      shortDescEn: 'The gem of the south with stunning mountain scenery',
      image: 'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Asir Region', regionAr: 'منطقة عسير',
      population: '400,000', area: '76,693 كم²',
      timezone: 'AST (UTC+3)', climate: 'Mild & Cool', climateAr: 'معتدل وبارد',
      rating: 4.7, reviewCount: 6800, featured: true,
      tags: ['mountains', 'nature', 'heritage', 'cool'],
      tagsAr: ['جبال', 'طبيعة', 'تراث', 'معتدل'],
      coordinates: { lat: 18.2164, lng: 42.5053 },
      bestTimeToVisit: 'Year-round', bestTimeToVisitAr: 'طوال السنة',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 30, hotelCount: 85, restaurantCount: 200, eventCount: 15,
    },
    {
      id: '5', nameAr: 'نيوم', nameEn: 'NEOM',
      descriptionAr: 'مدينة المستقبل على شاطئ البحر الأحمر، مشروع طموح يعيد تعريف الحياة الحضرية ويستشرف آفاق الغد. موطن ذا لاين، مدينة المستقبل الخطية.',
      descriptionEn: 'The city of the future on the Red Sea coast, an ambitious project redefining urban living and envisioning tomorrow. Home to THE LINE, the linear city of the future.',
      shortDescAr: 'مدينة المستقبل على البحر الأحمر',
      shortDescEn: 'The city of the future on the Red Sea',
      image: 'https://images.unsplash.com/photo-1675185439226-c5ad48c75c39?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1675185439226-c5ad48c75c39?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Tabuk Region', regionAr: 'منطقة تبوك',
      population: 'Under Construction', area: '26,500 كم²',
      timezone: 'AST (UTC+3)', climate: 'Coastal', climateAr: 'ساحلي',
      rating: 5.0, reviewCount: 3200, featured: true,
      tags: ['future', 'tech', 'innovation', 'luxury'],
      tagsAr: ['مستقبل', 'تقنية', 'ابتكار', 'فاخر'],
      coordinates: { lat: 28.0339, lng: 35.1563 },
      bestTimeToVisit: 'November - April', bestTimeToVisitAr: 'نوفمبر - أبريل',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 8, hotelCount: 12, restaurantCount: 30, eventCount: 5,
    },
    {
      id: '6', nameAr: 'الدمام', nameEn: 'Dammam',
      descriptionAr: 'عاصمة المنطقة الشرقية وبوابة الخليج العربي، مدينة نابضة بالحياة على ساحل الخليج. تتميز بمرافقها الحديثة وكورنيشها الجميل.',
      descriptionEn: 'Capital of the Eastern Province and gateway to the Arabian Gulf, Dammam is a vibrant city on the Gulf coast. Distinguished by its modern facilities and beautiful corniche.',
      shortDescAr: 'عاصمة المنطقة الشرقية وبوابة الخليج',
      shortDescEn: 'Capital of the Eastern Province and Gulf gateway',
      image: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Eastern Province', regionAr: 'المنطقة الشرقية',
      population: '1.1 مليون', area: '664 كم²',
      timezone: 'AST (UTC+3)', climate: 'Hot & Humid', climateAr: 'حار رطب',
      rating: 4.4, reviewCount: 5600, featured: false,
      tags: ['coastal', 'business', 'gulf', 'modern'],
      tagsAr: ['ساحلية', 'أعمال', 'خليج', 'حديثة'],
      coordinates: { lat: 26.4207, lng: 50.0888 },
      bestTimeToVisit: 'November - March', bestTimeToVisitAr: 'نوفمبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 20, hotelCount: 120, restaurantCount: 400, eventCount: 10,
    },
    {
      id: '7', nameAr: 'الطائف', nameEn: 'Taif',
      descriptionAr: 'مدينة الورود والثمر والهواء العليل، تقع على سفوح جبال الحجاز. تشتهر بزراعة الورد الطائفي العطري الذي يصنع منه أفخر أنواع العطور.',
      descriptionEn: 'The city of roses, fruits, and fresh air, nestled in the foothills of the Hejaz Mountains. Famous for growing the Taif rose, which produces the finest perfumes.',
      shortDescAr: 'مدينة الورود والهواء العليل',
      shortDescEn: 'City of roses and fresh mountain air',
      image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Makkah Region', regionAr: 'منطقة مكة المكرمة',
      population: '800,000', area: '18,400 كم²',
      timezone: 'AST (UTC+3)', climate: 'Moderate', climateAr: 'معتدل',
      rating: 4.5, reviewCount: 5200, featured: false,
      tags: ['roses', 'nature', 'mountains', 'fresh'],
      tagsAr: ['ورود', 'طبيعة', 'جبال', 'هواء'],
      coordinates: { lat: 21.2703, lng: 40.4158 },
      bestTimeToVisit: 'Year-round', bestTimeToVisitAr: 'طوال السنة',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 18, hotelCount: 70, restaurantCount: 250, eventCount: 8,
    },
    {
      id: '8', nameAr: 'حائل', nameEn: 'Hail',
      descriptionAr: 'مدينة الكرم والسخاء في شمال المملكة، تتميز بطبيعتها الصحراوية الرائعة وجبالها الشامخة. تُعرف بتراثها العريق وصحراء النفود الكبير.',
      descriptionEn: 'City of generosity in northern Saudi Arabia, distinguished by its stunning desert nature and towering mountains. Known for its ancient heritage and the Great Nefud Desert.',
      shortDescAr: 'مدينة الكرم وبوابة الشمال',
      shortDescEn: 'City of generosity and the Northern gateway',
      image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Hail Region', regionAr: 'منطقة حائل',
      population: '700,000', area: '103,887 كم²',
      timezone: 'AST (UTC+3)', climate: 'Desert', climateAr: 'صحراوي',
      rating: 4.3, reviewCount: 2800, featured: false,
      tags: ['desert', 'heritage', 'adventure', 'north'],
      tagsAr: ['صحراء', 'تراث', 'مغامرة', 'شمال'],
      coordinates: { lat: 27.5114, lng: 41.7208 },
      bestTimeToVisit: 'October - March', bestTimeToVisitAr: 'أكتوبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 15, hotelCount: 40, restaurantCount: 120, eventCount: 6,
    },
    {
      id: '9', nameAr: 'الأحساء', nameEn: 'Al Ahsa',
      descriptionAr: 'أكبر واحة نخيل في العالم ومنطقة تراثية مدرجة على قائمة اليونسكو، تتميز بعيونها المتدفقة وبحيراتها الجمالية وتراثها الحضاري الضارب في القدم.',
      descriptionEn: 'The world\'s largest palm oasis and a UNESCO World Heritage listed region, featuring flowing springs, scenic lakes, and a deep civilizational heritage.',
      shortDescAr: 'أكبر واحة نخيل في العالم',
      shortDescEn: 'The world\'s largest palm oasis',
      image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Eastern Province', regionAr: 'المنطقة الشرقية',
      population: '1.2 مليون', area: '5,800 كم²',
      timezone: 'AST (UTC+3)', climate: 'Hot & Dry', climateAr: 'حار وجاف',
      rating: 4.5, reviewCount: 4100, featured: false,
      tags: ['UNESCO', 'oasis', 'heritage', 'nature'],
      tagsAr: ['يونسكو', 'واحة', 'تراث', 'طبيعة'],
      coordinates: { lat: 25.3831, lng: 49.5862 },
      bestTimeToVisit: 'November - March', bestTimeToVisitAr: 'نوفمبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 25, hotelCount: 55, restaurantCount: 180, eventCount: 9,
    },
    {
      id: '10', nameAr: 'جازان', nameEn: 'Jazan',
      descriptionAr: 'جنة الجنوب الغربي وبوابة جزر فرسان الرائعة، تتميز بطبيعتها الاستوائية الخضراء وشواطئها البكر وأحشائها البحرية الغنية.',
      descriptionEn: 'Paradise of the southwest and gateway to the spectacular Farasan Islands, characterized by its lush tropical nature, pristine beaches, and rich marine life.',
      shortDescAr: 'جنة الجنوب وبوابة جزر فرسان',
      shortDescEn: 'Paradise of the south and gateway to Farasan Islands',
      image: 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1559494007-9f5847c49d94?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Jazan Region', regionAr: 'منطقة جازان',
      population: '500,000', area: '11,671 كم²',
      timezone: 'AST (UTC+3)', climate: 'Tropical', climateAr: 'استوائي',
      rating: 4.4, reviewCount: 3600, featured: false,
      tags: ['tropical', 'islands', 'diving', 'nature'],
      tagsAr: ['استوائي', 'جزر', 'غوص', 'طبيعة'],
      coordinates: { lat: 16.8892, lng: 42.5502 },
      bestTimeToVisit: 'November - March', bestTimeToVisitAr: 'نوفمبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 18, hotelCount: 45, restaurantCount: 150, eventCount: 7,
    },
    {
      id: '11', nameAr: 'الخبر', nameEn: 'Al Khobar',
      descriptionAr: 'مدينة الحياة العصرية على الخليج، تتميز بكورنيشها الساحر وأسواقها التجارية الراقية ومطاعمها المتنوعة. تعتبر من أكثر مدن المملكة تطوراً وعصرنة.',
      descriptionEn: 'Modern lifestyle city on the Gulf, distinguished by its charming corniche, upscale commercial centers, and diverse restaurants. Considered one of the most developed and modern cities in the Kingdom.',
      shortDescAr: 'مدينة الحياة العصرية على الخليج',
      shortDescEn: 'Modern lifestyle city on the Arabian Gulf',
      image: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
      images: [
        'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=80',
      ],
      region: 'Eastern Province', regionAr: 'المنطقة الشرقية',
      population: '400,000', area: '139 كم²',
      timezone: 'AST (UTC+3)', climate: 'Hot & Humid', climateAr: 'حار رطب',
      rating: 4.4, reviewCount: 4200, featured: false,
      tags: ['modern', 'coastal', 'shopping', 'dining'],
      tagsAr: ['حديثة', 'ساحلية', 'تسوق', 'مطاعم'],
      coordinates: { lat: 26.2172, lng: 50.1971 },
      bestTimeToVisit: 'November - March', bestTimeToVisitAr: 'نوفمبر - مارس',
      currency: 'SAR', language: 'Arabic',
      attractionCount: 16, hotelCount: 90, restaurantCount: 350, eventCount: 8,
    },
  ];

  readonly attractions: Attraction[] = [
    {
      id: 'a1', nameAr: 'برج المملكة', nameEn: 'Kingdom Tower',
      descriptionAr: 'أيقونة الرياض وأحد أطول الأبراج في المملكة العربية السعودية، يتميز بجسر الرؤية السماوي في قمته وإطلالة بانورامية مذهلة على العاصمة.',
      descriptionEn: 'The icon of Riyadh and one of the tallest towers in Saudi Arabia, featuring a Sky Bridge at its peak and stunning panoramic views of the capital.',
      image: 'https://images.unsplash.com/photo-1630501594958-b40d4f2adc95?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1630501594958-b40d4f2adc95?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'entertainment', categoryAr: 'ترفيه',
      rating: 4.6, reviewCount: 8200, price: 75, priceType: 'paid',
      duration: '2-3h', durationAr: '2-3 ساعات',
      openingHours: '10am - 10pm', openingHoursAr: '10ص - 10م',
      coordinates: { lat: 24.7116, lng: 46.6741 },
      tags: ['tower', 'views', 'shopping'], tagsAr: ['برج', 'إطلالات', 'تسوق'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a2', nameAr: 'حديقة الحيوانات الوطنية', nameEn: 'Riyadh Zoo',
      descriptionAr: 'أكبر حديقة حيوانات في المملكة العربية السعودية، تضم مئات الأنواع من الحيوانات النادرة وتوفر تجربة ترفيهية تعليمية للعائلات.',
      descriptionEn: 'The largest zoo in Saudi Arabia, housing hundreds of rare animal species and providing an educational entertainment experience for families.',
      image: 'https://images.unsplash.com/photo-1544985361-b420d7a77043?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1544985361-b420d7a77043?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'nature', categoryAr: 'طبيعة',
      rating: 4.3, reviewCount: 5600, price: 30, priceType: 'paid',
      duration: '3-4h', durationAr: '3-4 ساعات',
      openingHours: '9am - 9pm', openingHoursAr: '9ص - 9م',
      coordinates: { lat: 24.6832, lng: 46.7106 },
      tags: ['animals', 'family', 'nature'], tagsAr: ['حيوانات', 'عائلة', 'طبيعة'],
      featured: false, isFavorite: false,
    },
    {
      id: 'a3', nameAr: 'الحي التاريخي بالدرعية', nameEn: 'Historic Diriyah',
      descriptionAr: 'مهد الدولة السعودية ومدينة التراث بامتياز، مدرجة على قائمة التراث العالمي لليونسكو. تضم قصر سلوى والطين الشامخة التي تروي تاريخ المملكة.',
      descriptionEn: 'The cradle of Saudi Arabia and a heritage city par excellence, listed on the UNESCO World Heritage List. It includes Salwa Palace and the towering mud structures that tell the story of the Kingdom.',
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'heritage', categoryAr: 'تراث',
      rating: 4.8, reviewCount: 9400, price: 0, priceType: 'free',
      duration: '3-5h', durationAr: '3-5 ساعات',
      openingHours: '9am - 11pm', openingHoursAr: '9ص - 11م',
      coordinates: { lat: 24.7345, lng: 46.5727 },
      tags: ['UNESCO', 'heritage', 'history'], tagsAr: ['يونسكو', 'تراث', 'تاريخ'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a4', nameAr: 'حي البلد التاريخي', nameEn: 'Al-Balad Historic District',
      descriptionAr: 'قلب جدة العريق المدرج على لائحة التراث العالمي، يتميز بمبانيه الحجرية ذات الأسقف الخشبية المنحوتة والشرفات التقليدية المسماة بالرواشين.',
      descriptionEn: 'The ancient heart of Jeddah, a UNESCO World Heritage Site, distinguished by its stone buildings with carved wooden ceilings and traditional balconies known as Rawasheen.',
      image: 'https://images.unsplash.com/photo-1596622956974-30cc9bcc5d4c?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1596622956974-30cc9bcc5d4c?auto=format&fit=crop&w=800&q=80'],
      cityId: '2', cityNameAr: 'جدة', cityNameEn: 'Jeddah',
      category: 'heritage', categoryAr: 'تراث',
      rating: 4.7, reviewCount: 11200, price: 0, priceType: 'free',
      duration: '2-4h', durationAr: '2-4 ساعات',
      openingHours: 'Open 24h', openingHoursAr: 'مفتوح 24 ساعة',
      coordinates: { lat: 21.4858, lng: 39.1855 },
      tags: ['UNESCO', 'heritage', 'architecture'], tagsAr: ['يونسكو', 'تراث', 'معمار'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a5', nameAr: 'مدائن صالح (الحِجر)', nameEn: 'Hegra (Madain Saleh)',
      descriptionAr: 'أول موقع سعودي يُدرج على قائمة التراث العالمي لليونسكو، يضم أكثر من 100 مقبرة نبطية محفورة في الصخر يعود تاريخها إلى القرن الأول الميلادي.',
      descriptionEn: 'Saudi Arabia\'s first UNESCO World Heritage Site, featuring over 100 Nabataean rock-cut tombs dating back to the 1st century AD.',
      image: 'https://images.unsplash.com/photo-1590764508404-09c67fff4358?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1590764508404-09c67fff4358?auto=format&fit=crop&w=800&q=80'],
      cityId: '3', cityNameAr: 'العُلا', cityNameEn: 'AlUla',
      category: 'heritage', categoryAr: 'تراث',
      rating: 4.9, reviewCount: 6800, price: 95, priceType: 'paid',
      duration: '4-6h', durationAr: '4-6 ساعات',
      openingHours: '8am - 6pm', openingHoursAr: '8ص - 6م',
      coordinates: { lat: 26.7867, lng: 37.9528 },
      tags: ['UNESCO', 'Nabataean', 'ancient'], tagsAr: ['يونسكو', 'نبطي', 'قديم'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a6', nameAr: 'واجهة جدة البحرية', nameEn: 'Jeddah Corniche',
      descriptionAr: 'ممشى بحري يمتد لأكثر من 30 كيلومتراً على ساحل البحر الأحمر، يضم حديقة الفهد الملكية ونافورة جدة الشهيرة وأجمل المتنزهات الساحلية.',
      descriptionEn: 'A waterfront promenade stretching over 30 km along the Red Sea coast, featuring the Royal Fahd Park, the famous Jeddah Fountain, and beautiful coastal parks.',
      image: 'https://images.unsplash.com/photo-1527168027773-0cc890c4f42e?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1527168027773-0cc890c4f42e?auto=format&fit=crop&w=800&q=80'],
      cityId: '2', cityNameAr: 'جدة', cityNameEn: 'Jeddah',
      category: 'nature', categoryAr: 'طبيعة',
      rating: 4.5, reviewCount: 14200, price: 0, priceType: 'free',
      duration: '2-3h', durationAr: '2-3 ساعات',
      openingHours: 'Open 24h', openingHoursAr: 'مفتوح 24 ساعة',
      coordinates: { lat: 21.5433, lng: 39.1728 },
      tags: ['beach', 'walking', 'fountain'], tagsAr: ['شاطئ', 'مشي', 'نافورة'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a7', nameAr: 'تلفريك أبها', nameEn: 'Abha Cable Car',
      descriptionAr: 'تجربة فريدة من نوعها في تلال أبها الخضراء، ينقلك التلفريك فوق غابات السدر والأودية الخضراء ليمنحك إطلالات بانورامية لا تُنسى على المدينة والجبال المحيطة.',
      descriptionEn: 'A unique experience in the green hills of Abha, the cable car transports you over Sidr forests and green valleys, offering unforgettable panoramic views of the city and surrounding mountains.',
      image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=800&q=80'],
      cityId: '4', cityNameAr: 'أبها', cityNameEn: 'Abha',
      category: 'adventure', categoryAr: 'مغامرة',
      rating: 4.7, reviewCount: 4600, price: 60, priceType: 'paid',
      duration: '1-2h', durationAr: '1-2 ساعة',
      openingHours: '9am - 11pm', openingHoursAr: '9ص - 11م',
      coordinates: { lat: 18.2313, lng: 42.4932 },
      tags: ['cable-car', 'views', 'adventure'], tagsAr: ['تلفريك', 'مناظر', 'مغامرة'],
      featured: true, isFavorite: false,
    },
    {
      id: 'a8', nameAr: 'متحف الرياض الوطني', nameEn: 'National Museum of Riyadh',
      descriptionAr: 'أكبر متحف في منطقة الخليج، يمتد على مساحة ضخمة ويروي قصة الجزيرة العربية عبر ثمانية أجنحة تعليمية تبدأ من عصور ما قبل التاريخ وحتى العصر الحديث.',
      descriptionEn: 'The largest museum in the Gulf region, spanning a vast area and telling the story of the Arabian Peninsula through eight educational halls from prehistoric times to the modern era.',
      image: 'https://images.unsplash.com/photo-1566127992631-137a642a90f4?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1566127992631-137a642a90f4?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'museum', categoryAr: 'متحف',
      rating: 4.6, reviewCount: 7800, price: 0, priceType: 'free',
      duration: '3-4h', durationAr: '3-4 ساعات',
      openingHours: '9am - 9pm', openingHoursAr: '9ص - 9م',
      coordinates: { lat: 24.6877, lng: 46.7200 },
      tags: ['museum', 'history', 'education'], tagsAr: ['متحف', 'تاريخ', 'تعليم'],
      featured: false, isFavorite: false,
    },
  ];

  readonly events: TourismEvent[] = [
    {
      id: 'e1', titleAr: 'موسم الرياض', titleEn: 'Riyadh Season',
      descriptionAr: 'أكبر موسم ترفيهي في تاريخ المملكة العربية السعودية، يجمع بين المنافسات الرياضية الدولية والحفلات الموسيقية والمعارض الفنية والمطاعم العالمية.',
      descriptionEn: 'The largest entertainment season in Saudi Arabia\'s history, bringing together international sports competitions, concerts, art exhibitions, and world-class restaurants.',
      image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'entertainment', categoryAr: 'ترفيه',
      startDate: '2024-10-01', endDate: '2025-03-31',
      venue: 'Multiple Venues - Riyadh', venueAr: 'مواقع متعددة - الرياض',
      price: 0, priceType: 'free',
      organizer: 'General Entertainment Authority',
      tags: ['festival', 'entertainment', 'sports', 'music'], tagsAr: ['مهرجان', 'ترفيه', 'رياضة', 'موسيقى'],
      featured: true, isFavorite: false, attendeeCount: 15000000,
    },
    {
      id: 'e2', titleAr: 'موسم جدة', titleEn: 'Jeddah Season',
      descriptionAr: 'موسم ترفيهي بحري فريد على ساحل البحر الأحمر، يقدم أنشطة الغوص والرياضات البحرية والحفلات الموسيقية وفعاليات الطهي العالمية.',
      descriptionEn: 'A unique maritime entertainment season on the Red Sea coast, offering diving activities, water sports, musical concerts, and international culinary events.',
      image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80'],
      cityId: '2', cityNameAr: 'جدة', cityNameEn: 'Jeddah',
      category: 'festival', categoryAr: 'مهرجان',
      startDate: '2024-11-01', endDate: '2025-02-28',
      venue: 'Jeddah Waterfront', venueAr: 'كورنيش جدة',
      price: 0, priceType: 'free',
      organizer: 'Jeddah Season Authority',
      tags: ['festival', 'coastal', 'music'], tagsAr: ['مهرجان', 'ساحلي', 'موسيقى'],
      featured: true, isFavorite: false, attendeeCount: 8000000,
    },
    {
      id: 'e3', titleAr: 'مهرجان العُلا الموسيقي', titleEn: 'AlUla Music Festival',
      descriptionAr: 'مهرجان موسيقي استثنائي وسط الصخور النبطية، يجمع بين ألحان الموسيقى الكلاسيكية والتراثية في أجواء سحرية لا مثيل لها في العالم.',
      descriptionEn: 'An exceptional music festival amidst Nabataean rocks, combining classical and heritage music in a magical atmosphere unlike anything in the world.',
      image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=80'],
      cityId: '3', cityNameAr: 'العُلا', cityNameEn: 'AlUla',
      category: 'music', categoryAr: 'موسيقى',
      startDate: '2025-01-15', endDate: '2025-01-20',
      venue: 'Hegra Arena', venueAr: 'ساحة الحجر',
      price: 250, priceType: 'paid',
      organizer: 'RCU AlUla',
      tags: ['music', 'heritage', 'culture'], tagsAr: ['موسيقى', 'تراث', 'ثقافة'],
      featured: true, isFavorite: false, attendeeCount: 12000,
    },
    {
      id: 'e4', titleAr: 'سباق الفورمولا 1 السعودي', titleEn: 'Saudi Arabian Grand Prix',
      descriptionAr: 'سباق الفورمولا 1 الأسرع في تاريخ البطولة، يُقام على حلبة جدة الشاطئية الليلية المطلة على البحر الأحمر، ويجذب الملايين من محبي سباقات السيارات حول العالم.',
      descriptionEn: 'The fastest Formula 1 race in championship history, held on the Jeddah Corniche Circuit overlooking the Red Sea, attracting millions of motorsport fans worldwide.',
      image: 'https://images.unsplash.com/photo-1558981852-426c373d4324?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1558981852-426c373d4324?auto=format&fit=crop&w=800&q=80'],
      cityId: '2', cityNameAr: 'جدة', cityNameEn: 'Jeddah',
      category: 'sports', categoryAr: 'رياضة',
      startDate: '2025-03-21', endDate: '2025-03-23',
      venue: 'Jeddah Corniche Circuit', venueAr: 'حلبة جدة الشاطئية',
      price: 500, priceType: 'paid',
      organizer: 'Saudi Motorsport Company',
      tags: ['F1', 'racing', 'sports'], tagsAr: ['فورمولا1', 'سباق', 'رياضة'],
      featured: true, isFavorite: false, attendeeCount: 150000,
    },
    {
      id: 'e5', titleAr: 'مهرجان تمور الأحساء', titleEn: 'Al Ahsa Dates Festival',
      descriptionAr: 'مهرجان سنوي يحتفي بأجود أنواع التمور السعودية في واحة الأحساء، يضم معارض للتمور النادرة ومنتجات النخيل والتراث الحضاري لمنطقة الأحساء.',
      descriptionEn: 'An annual festival celebrating the finest Saudi dates in the Al Ahsa oasis, featuring exhibitions of rare dates, palm products, and the cultural heritage of the Al Ahsa region.',
      image: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=800&q=80'],
      cityId: '9', cityNameAr: 'الأحساء', cityNameEn: 'Al Ahsa',
      category: 'food', categoryAr: 'طعام',
      startDate: '2025-09-15', endDate: '2025-09-25',
      venue: 'Al Ahsa Exhibition Center', venueAr: 'مركز المعارض - الأحساء',
      price: 0, priceType: 'free',
      organizer: 'Al Ahsa Municipality',
      tags: ['dates', 'heritage', 'food', 'culture'], tagsAr: ['تمور', 'تراث', 'طعام', 'ثقافة'],
      featured: false, isFavorite: false, attendeeCount: 80000,
    },
    {
      id: 'e6', titleAr: 'معرض الرياض الدولي للكتاب', titleEn: 'Riyadh International Book Fair',
      descriptionAr: 'أحد أكبر المعارض الدولية للكتاب في الشرق الأوسط، يضم مئات آلاف العناوين من أكثر من 50 دولة ويستقطب ملايين الزوار من المثقفين وعشاق القراءة.',
      descriptionEn: 'One of the largest international book fairs in the Middle East, featuring hundreds of thousands of titles from over 50 countries and attracting millions of visitors.',
      image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80',
      images: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80'],
      cityId: '1', cityNameAr: 'الرياض', cityNameEn: 'Riyadh',
      category: 'art', categoryAr: 'فنون',
      startDate: '2025-02-26', endDate: '2025-03-08',
      venue: 'Riyadh International Convention Center', venueAr: 'مركز الرياض الدولي للمؤتمرات',
      price: 0, priceType: 'free',
      organizer: 'Ministry of Culture',
      tags: ['books', 'culture', 'education'], tagsAr: ['كتب', 'ثقافة', 'تعليم'],
      featured: false, isFavorite: false, attendeeCount: 2000000,
    },
  ];

  getCityById(id: string): City | undefined {
    return this.cities.find(c => c.id === id);
  }

  getAttractionsByCityId(cityId: string): Attraction[] {
    return this.attractions.filter(a => a.cityId === cityId);
  }

  getEventsByCityId(cityId: string): TourismEvent[] {
    return this.events.filter(e => e.cityId === cityId);
  }

  getFeaturedCities(): City[] {
    return this.cities.filter(c => c.featured);
  }

  getFeaturedAttractions(): Attraction[] {
    return this.attractions.filter(a => a.featured);
  }

  getFeaturedEvents(): TourismEvent[] {
    return this.events.filter(e => e.featured);
  }

  searchCities(query: string): City[] {
    const q = query.toLowerCase();
    return this.cities.filter(c =>
      c.nameAr.includes(query) || c.nameEn.toLowerCase().includes(q) ||
      c.tags.some(t => t.includes(q)) || c.tagsAr.some(t => t.includes(query))
    );
  }

  searchAttractions(query: string): Attraction[] {
    const q = query.toLowerCase();
    return this.attractions.filter(a =>
      a.nameAr.includes(query) || a.nameEn.toLowerCase().includes(q) ||
      a.categoryAr.includes(query) || a.category.toLowerCase().includes(q)
    );
  }
}
